refresh_rate = "30 seconds"

[appenders.stdout]
kind = "console"

[appenders.stdout.encoder]
kind = "pattern"
pattern = "{d(%Y-%m-%d %H:%M:%S)} [{l}] - {m}{n}"

[appenders.rolling_file]
kind = "rolling_file"
path = "log/phetools.log"

[appenders.rolling_file.encoder]
kind = "pattern"
pattern = "{d} [{l}] [{t}] - {m}{n}"

[appenders.rolling_file.policy]
kind = "compound"

[appenders.rolling_file.policy.trigger]
kind = "size"
limit = "20 mb"



[appenders.rolling_file.policy.roller]
kind = "delete"

[root]
level = "trace"
appenders = ["stdout", "rolling_file"]