name: Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true

       # Ensure compatible rayon for graph_builder
      - name: Force compatible rayon version
        run: |
          echo '[patch.crates-io]' >> Cargo.toml
          echo 'rayon = "=1.10.0"' >> Cargo.toml

      # Build Rust code (ensures deps compile in CI)
      - name: Build project
        run: cargo build --release --locked

      - name: Install mdBook
        run: cargo install mdbook --version 0.4.40 --locked

      - name: Build API docs
        run: cargo doc --no-deps --release

      - name: Build mdBook
        run: mdbook build book

      - name: Copy API docs into mdBook output
        run: |
          mkdir -p book/book/api
          cp -r target/doc/* book/book/api/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book/book

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
